### PR TITLE
Removing paragraph

### PR DESCRIPTION
**Pull request by iPoolito**

### CODE REVIEW

**Comment by iPoolito** [comment]
Looks good to me :)

**Comment by XES4R** [comment]
it sucks! just kidding! nice Profe!

**Comment by JhosNadhir** [comment]
to production

**Comment by SebastianAguilar12** [comment]
that's fine!

**Comment by FSilvaV** [comment]
se ve bien los cambios. no rompe nada, todavia jajaj

**Comment by H3CT0RV1LL2RR32L** [comment]
Excellent class

**Pull request merged**
